---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels:
        app: beginnerpy
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 5000
        name: http
    selector:
        app: beginnerpy
        tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: frontend
    labels:
        app: beginnerpy
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt"
spec:
    tls:
      - hosts:
        - beginnerpy.com
        secretName: beginnerpy-cert
    rules:
      - host: beginnerpy.com
        http:
            paths:
              - backend:
                    serviceName: frontend
                    servicePort: 5000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  targetCPUUtilizationPercentage: 70
