apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
  labels:
    app: beginnerpy
spec:
  selector:
    matchLabels:
      app: beginnerpy
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: beginnerpy
        tier: frontend
    spec:
      containers:
      - name: flask-site
        image: zzmmrmn/beginnerpy-site:0.0.2
        env:
          - name: PRODUCTION
            value: "PRODUCTION"
          - name: "DB_HOST"
            value: "private-personal-postgres-cluster-1-apr-26-backup-do-user-87772.a.db.ondigitalocean.com"
          - name: "DB_PORT"
            value: "25060"
          - name: "DB_NAME"
            value: "bpydb"
          - name: "DB_USER"
            value: "beginnerpy"
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: beginnerpy
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: beginnerpy
    tier: frontend
